# Generated by Django 2.2.28 on 2023-01-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='creared',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descriptions',
            new_name='description',
        ),
    ]
