# Generated by Django 2.2.28 on 2023-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230122_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('gr', '#4bb481'), ('yw', '#dbc124'), ('rd', '#d0472f')], default='gr', max_length=2, verbose_name='Важность'),
        ),
    ]
